import {ApplicationConfig, provideZoneChangeDetection} from '@angular/core';
import {provideRouter} from '@angular/router';

import {routes} from './app.routes';
import {provideClientHydration} from '@angular/platform-browser';
import {provideAnimationsAsync} from '@angular/platform-browser/animations/async';
import {providePrimeNG} from 'primeng/config';
import {provideHttpClient, withFetch} from '@angular/common/http';
import Aura from '@primeuix/themes/aura';

export const appConfig: ApplicationConfig = {
  providers: [provideZoneChangeDetection({eventCoalescing: true}),
    provideRouter(routes),
    provideClientHydration(),
    provideAnimationsAsync(),
    providePrimeNG({
      theme: {
        preset: Aura,
      },
      translation: {
        "accept": "بله",
        "addRule": "افزودن قانون",
        "am": "قبل از ظهر",
        "apply": "درخواست دادن",
        "cancel": "لغو",
        "choose": "انتخاب",
        "chooseDate": "انتخاب تاریخ",
        "chooseMonth": "انتخاب ماه",
        "chooseYear": "انتخاب تاریخ",
        "clear": "پاک کردن",
        "contains": "حاوی",
        "dateAfter": "تاریخ بعد است",
        "dateBefore": "تاریخ قبل است",
        "dateFormat": "yy/mm/dd",
        "dateIs": "تاریخ است",
        "dateIsNot": "تاریخ نیست",
        "dayNames": [
          "یکشنبه",
          "دوشنبه",
          "سه‌شنبه",
          "چهارشنبه",
          "پنجشنبه",
          "جمعه",
          "شنبه"
        ],
        "dayNamesMin": [
          "ی",
          "د",
          "س",
          "چ",
          "پ",
          "ج",
          "ش"
        ],
        "dayNamesShort": [
          "ی",
          "د",
          "س",
          "چ",
          "پ",
          "ج",
          "ش"
        ],
        "emptyFilterMessage": "نتیجه ای پیدا نشد",
        "emptyMessage": "هیچ گزینه ای در دسترس نیست",
        "emptySearchMessage": "نتیجه ای پیدا نشد",
        "emptySelectionMessage": "موردی انتخاب نشده",
        "endsWith": "پایان با",
        "equals": "برابر",
        "fileChosenMessage": "{0} فایل",
        "fileSizeTypes": [
          "B",
          "KB",
          "MB",
          "GB",
          "TB",
          "PB",
          "EB",
          "ZB",
          "YB"
        ],
        "firstDayOfWeek": 6,
        "gt": "بیشتر از",
        "gte": "برابر یا بیشتر از",
        "lt": "کمتر از",
        "lte": "برابر یا کمتر از",
        "matchAll": "مطابقت با همه",
        "matchAny": "مطابقت با هر",
        "medium": "متوسط",
        "monthNames": [
          "ژانویه",
          "فوریه",
          "مارس",
          "آوریل",
          "مه",
          "ژوئن",
          "ژوئیه",
          "اوت",
          "سپتامبر",
          "اکتبر",
          "نوامبر",
          "دسامبر"
        ],
        "monthNamesShort": [
          "ژانویه",
          "فوریه",
          "مارس",
          "آوریل",
          "مه",
          "ژوئن",
          "ژوئیه",
          "اوت",
          "سپتامبر",
          "اکتبر",
          "نوامبر",
          "دسامبر"
        ],
        "nextDecade": "دهه بعد",
        "nextHour": "ساعت بعد",
        "nextMinute": "دقیقه بعد",
        "nextMonth": "ماه بعد",
        "nextSecond": "ثانیه بعد",
        "nextYear": "سال بعد",
        "noFileChosenMessage": "هیچ فایلی انتخاب نشد",
        "noFilter": "بدون فیلتر",
        "notContains": "حاوی نیست",
        "notEquals": "نا برابر",
        "passwordPrompt": "یک گذرواژه وارد کنید",
        "pending": "در انتظار",
        "pm": "بعد از ظهر",
        "prevDecade": "دهه قبل",
        "prevHour": "ساعت قبل",
        "prevMinute": "دقیقه قبل",
        "prevMonth": "ماه قبل",
        "prevSecond": "ثانیه قبل",
        "prevYear": "سال قبل",
        "reject": "خیر",
        "removeRule": "حذف قانون",
        "searchMessage": "{0} نتیجه در دسترس است",
        "selectionMessage": "{0} موارد انتخاب شده",
        "startsWith": "شروع با",
        "strong": "قوی",
        "today": "امروز",
        "upload": "بارگذاری",
        "weak": "ضعیف",
        "weekHeader": "هفته",
        "aria": {
          "cancelEdit": "لغو ویرایش",
          "close": "بستن",
          "collapseRow": "ردیف جمع شد",
          "editRow": "ویرایش ردیف",
          "expandRow": "ردیف گسترش پیدا کرده",
          "falseLabel": "غلط",
          "filterConstraint": "محدودیت فیلتر",
          "filterOperator": "عملگر فیلتر",
          "firstPageLabel": "اولین صفحه",
          "gridView": "نمایش به صورت شبکه",
          "hideFilterMenu": "پنهان کردن فیلتر ها",
          "jumpToPageDropdownLabel": "پرش به دراپ داون صفحه",
          "jumpToPageInputLabel": "پرش به ورودی صفحه",
          "lastPageLabel": "آخرین صفحه",
          "listLabel": "لیست گزینه ها",
          "listView": "نمایش به صورت لیست",
          "maximizeLabel": "حداکثر کردن",
          "moveAllToSource": "حرکت همه تا منبع",
          "moveAllToTarget": "حرکت همه تا هدف",
          "moveBottom": "حرکت پایین",
          "moveDown": "حرکت پایین",
          "moveTop": "حرکت بالا",
          "moveToSource": "حرکت تا منبع",
          "moveToTarget": "حرکت تا هدف",
          "moveUp": "حرکت بالا",
          "navigation": "جهت یابی",
          "next": "بعدی",
          "nextPageLabel": "صفحه بعد",
          "nullLabel": "انتخاب نشده",
          "pageLabel": "{page}",
          "previous": "قبلی",
          "prevPageLabel": "صفحه قبل",
          "removeLabel": "برداشتن",
          "rotateLeft": "چرخش به سمت چپ",
          "rotateRight": "چرخش به سمت راست",
          "rowsPerPageLabel": "ردیف در هر صفحه",
          "saveEdit": "ذخیره ویرایش",
          "scrollTop": "اسکرول بالا",
          "selectAll": "همه موارد انتخاب شدند",
          "selectColor": "یک رنگ انتخاب کنید",
          "selectRow": "ردیف انتخاب شده",
          "showFilterMenu": "نمایش فیلتر ها",
          "slide": "اسلاید",
          "slideNumber": "{slideNumber}",
          "star": "ستاره",
          "stars": "{star} ستاره",
          "trueLabel": "صحیح",
          "unselectAll": "همه موارد لغو انتخاب شدند",
          "unselectRow": "ردیف لغو انتخاب شد",
          "zoomImage": "بزرگنمایی تصویر",
          "zoomIn": "بزرگنمایی",
          "zoomOut": "کوچک نمایی"
        }
      },
    }),
    provideHttpClient(withFetch()),
  ]
};
